### ISSUE TITLE
添加简单模式—以医生游戏为例

### ISSUE THREAD

**Issue by simonkorl** [clappinggame/clappinggame#2]
拍手游戏有很多不同的版本。目前的版本比较复杂，也许我们可以先设计一个更为简单的模式来帮助玩家们上手。

比如说”医生游戏“（或者有其他的名字），只有以”挂号“为核心的攒气方式和对应各种攻击的防守手段。

具体的招式列表可以在之后再进行交流。

**Comment by cnzc** [comment]
可以
